### ISSUE TITLE
TypeError: Cannot read property 'border' of undefined

### ISSUE THREAD

**Issue by arjunattam** [fictoan/fictoan-react#46]
Hi, I was trying out the `Card` component example from fictoan.io, but ran into an issue. [CodeSandbox link](https://codesandbox.io/s/confident-shadow-i86xq?file=/src/App.js) for repro.

```
The above error occurred in the <CardStyled> component:
    at O (https://i86xq.csb.app/node_modules/styled-components/dist/styled-components.browser.esm.js:612:7)
    at eval (https://i86xq.csb.app/node_modules/fictoan-react/dist/index.es.js:342:12)
    at eval (https://i86xq.csb.app/node_modules/fictoan-react/dist/index.es.js:921:16)
    at MyComponent
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. 
    in Unknown

Error in sandbox: 
TypeError: Cannot read property 'border' of undefined
    at we.forwardRef.shadow (https://i86xq.csb.app/node_modules/fictoan-react/dist/index.es.js:920:82)
    at Ne (https://i86xq.csb.app/node_modules/styled-components/dist/styled-components.browser.esm.js:512:13)
    at e.generateAndInjectStyles (https://i86xq.csb.app/node_modules/styled-components/dist/styled-components.browser.esm.js:385:19)
    at eval (https://i86xq.csb.app/node_modules/styled-components/dist/styled-components.browser.esm.js:607:80)
    at eval (https://i86xq.csb.app/node_modules/styled-components/dist/styled-components.browser.esm.js:609:9)
    at O (https://i86xq.csb.app/node_modules/styled-components/dist/styled-components.browser.esm.js:612:7)
    at renderWithHooks (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:10021:22)
    at updateForwardRef (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11643:24)
    at beginWork (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12978:20)
    at HTMLUnknownElement.callCallback (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:2746:18)
    at Object.invokeGuardedCallbackDev (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:2770:20)
    at invokeGuardedCallback (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:2804:35)
    at beginWork$1 (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16114:11)
    at performUnitOfWork (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:15339:16)
    at workLoopSync (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:15293:9)
    at renderRootSync (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:15268:11)
    at performSyncWorkOnRoot (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:15008:22)
    at scheduleUpdateOnFiber (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:14770:11)
    at updateContainer (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17211:7)
    at eval (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17610:11)
    at unbatchedUpdates (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:15104:16)
    at legacyRenderSubtreeIntoContainer (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17609:9)
    at Object.render (https://i86xq.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17672:14)
    at evaluate (https://i86xq.csb.app/src/index.js:14:19)
    at H (https://codesandbox.io/static/js/sandbox.41ace9cd2.js:1:99575)
    at G.evaluate (https://codesandbox.io/static/js/sandbox.41ace9cd2.js:1:111943)
    at be.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.41ace9cd2.js:1:121879)
    at be.evaluateModule (https://codesandbox.io/static/js/sandbox.41ace9cd2.js:1:121378)
    at https://codesandbox.io/static/js/sandbox.41ace9cd2.js:1:295414
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
Could not consume error: 
Error: Something is *really* wrong.
```

**Comment by ghostwriternr** [comment]
Hi @arjunattam! Note to self and @sujan-s to improve our docs + error handling :smile: 

Fictoan requires that you wrap your tree with the exported `ThemeProvider` component. We use styled-components internally and this component provides the default (but override-able) theme to all child components via the context API. I've [forked your repro here to use ThemeProvider](https://codesandbox.io/s/youthful-cdn-1s2bv).
